### ISSUE TITLE
Fix tests

### ISSUE THREAD

**Issue by morgante** [terraform-google-modules/terraform-google-project-factory#105]
The CI tests merged still have outstanding issues:

- group_email is invalid: https://concourse.infra.cft.tips/teams/cft/pipelines/terraform-google-project-factory/jobs/integration-tests/builds/137#L5c267bbe:392

**Comment by aaron-lane** [comment]
Still broken on master: https://concourse.infra.cft.tips/teams/cft/pipelines/terraform-google-project-factory/jobs/integration-tests/builds/395#L5cb98c2e:505.

**Comment by aaron-lane** [comment]
I've looked in to this issue more.

The malformed `group_email` output is part of the minimal suite, not the full suite. The minimal suite does not use a G Suite group which is why this broken output is not causing a failure. The fix for this issue should be in the `gsuite_group` module, specifically at [this line](https://github.com/terraform-google-modules/terraform-google-project-factory/blob/master/modules/gsuite_group/main.tf#L20). If `var.name` is empty then `local.email` should also be empty. The associated integration test in the minimal suite should confirm that `group_email` is empty.

**Comment by alexkonkin** [comment]
Thank you for your review. 
I will remove my test from the full test suite and rewrite it according
to the approach that you mentioned in your previous reply
