### ISSUE TITLE
Allow import of GCP projects

### ISSUE THREAD

**Issue by ensslen** [terraform-google-modules/terraform-google-project-factory#138]
[GCP project names can not be reused](https://cloud.google.com/resource-manager/docs/creating-managing-projects#identifying_projects), attempting to do so results in a 409 error.  However, this module won't accept an imported project, e.g. `terraform import module.X.google_project.main my-project`, because `id` and `project_id` can not be supplied as inputs. The imported project results in 

> -/+ module.my-project.google_project.main (new resource required)
>       id:                            "my-project-name" => <computed> (forces new resource)
>       auto_create_network:           "true" => "false"
>       billing_account:               "XXXXX-XXXXX-XXXXX" => "XXXXX-XXXXX-XXXXX"
>       folder_id:                     "" => <computed>
>       name:                          "my-project-name" => "my-project-name"
>       number:                        "808999117972" => <computed>
>       org_id:                        "1234567890" => "1234567890"
>       policy_data:                   "" => <computed>
>       policy_etag:                   "" => <computed>
>       project_id:                    "my-project-name" => "${local.temp_project_id}" (forces new resource)
>       skip_delete:                   "" => <computed>

**Comment by aaron-lane** [comment]
Hi @ensslen. Thank you for your interest in the project! I apologize for the extreme delay in responding.

Since project-factory v2.1, `project_id` is an optional variable, but that only solves part of this problem as the ultimate value passed to the `google_project` has sufficient interpolation complexity to cause an imported project to be recreated even when its ID is provided as an input. We are investigating moving the complexity around the project ID calculation out of the `core-project-factory` submodule which should allow you to invoke that submodule directly with an imported project.

**Comment by nicobrinkkemper** [comment]
Can I fill in a existing project name without fear of losing the name? I fear it will be deleted and then won't be able to use that name anymore.

**Comment by aaron-lane** [comment]
@nicobrinkkemper support is not in place for importing existing projects.

**Comment by aaron-lane** [comment]
We should ensure that at least the `core_project_factory` submodule can be used with an imported project. If the root module, `shared_vpc` submodule, and `gsuite_enabled` submodules can be used with an imported project, that will be a bonus.

**Comment by paulpalamarchuk** [comment]
@aaron-lane I've tested imports with main module, `core_project_factory` and `shared_vpc` submodules. Works fine.
