### ISSUE TITLE
Refactor service activation

### ISSUE THREAD

**Issue by morgante** [terraform-google-modules/terraform-google-project-factory#282]
We need to improve service management in this module to address issues with duplication and potential race conditions.

We should:
1. Remove [authoritative mode](https://github.com/terraform-google-modules/terraform-google-project-factory/blob/master/modules/core_project_factory/main.tf#L165), as described in #279 
2. Update the [core_project_factory](https://github.com/terraform-google-modules/terraform-google-project-factory/blob/master/modules/core_project_factory/main.tf#L153) to use the [project_services module](https://github.com/terraform-google-modules/terraform-google-project-factory/tree/master/modules/project_services)
3. Update the project_services module to use `for_each` instead of `count`.
4. Provide a migration guide + script for Project Factory users to upgrade to the new version without any Terraform plan diff appearing. (cf. [this guide](https://github.com/terraform-google-modules/terraform-google-project-factory/blob/master/docs/upgrading_to_project_factory_v1.0.md#upgrading-to-project-factory-v10))

**Comment by ideasculptor** [comment]
Is it safe to assume that correcting this will correct the frequent error about attempting to delete the default service account when it is already deleted?  

Even if the dependencies that cause that script to fire too frequently are corrected, it would be good to rewrite the script so that it correctly handles being called against a service account that is already deleted, so that it won't result in an error, even if it is erroneously called by some future circumstance.

**Comment by morgante** [comment]
> Is it safe to assume that correcting this will correct the frequent error about attempting to delete the default service account when it is already deleted?

That seems like an unrelated issue which I haven't seen before. Would you mind opening a bug (and including your config + plan + logs)?
