### ISSUE TITLE
Version 6.2.0 fails on precondition if no Python3

### ISSUE THREAD

**Issue by Rycieos** [terraform-google-modules/terraform-google-project-factory#351]
New in version 6.2.0, in commit bdd1d94b3696e3c9a2c73e10465505ee2b728bc9, from PR #343, if either `pip3` or `python3` is not installed the build will fail.

```
module.my_project.module.project-factory.null_resource.preconditions: Creating...
module.my_project.module.project-factory.null_resource.preconditions: Provisioning with 'local-exec'...
module.my_project.module.project-factory.null_resource.preconditions (local-exec): Executing: ["pip3" "install" "-r" ".../.terraform/modules/my_project/terraform-google-modules-terraform-google-project-factory-c19c299/modules/core_project_factory/scripts/preconditions/requirements.txt"]
Error: Error running command '.../.terraform/modules/my_project/terraform-google-modules-terraform-google-project-factory-c19c299/modules/core_project_factory/scripts/preconditions/requirements.txt': exec: "pip3": executable file not found in $PATH. Output: 
```

These changes appear to have caused this:
https://github.com/terraform-google-modules/terraform-google-project-factory/commit/bdd1d94b3696e3c9a2c73e10465505ee2b728bc9#diff-d3740c193b3aa6f052c215e40f1a18ddL81
```
  provisioner "local-exec" {
    command     = local.pip_requirements_absolute_path
    interpreter = ["pip3", "install", "-r"]
-   on_failure  = "continue"
  }
```
https://github.com/terraform-google-modules/terraform-google-project-factory/commit/bdd1d94b3696e3c9a2c73e10465505ee2b728bc9#diff-d3740c193b3aa6f052c215e40f1a18ddL86
```
  provisioner "local-exec" {
    command = local.preconditions_command
-   on_failure = "continue"
    environment = {
      GRACEFUL_IMPORTERROR = "true"
    }
  }
```

Seems like a logical change, until you read the docs:
https://github.com/terraform-google-modules/terraform-google-project-factory/blob/cb94cd25b244b59f0e2b3bbb5587520a4b473736/README.md#L289-L293

Python 3 and/or pip3 isn't listed anywhere in the README as a dependency for this module. Therefore I would say that this change in v6.2.0 was an accidental breaking change. I think this "fail on no python3" change should be reverted for the 6.X releases, and if a `python3` dependency is wanted for the future, it's looked at for a breaking change.

**Comment by morgante** [comment]
This does indeed look like a regression. We should fix this and issue a patch release. @taylorludwig Can you take a look?

**Comment by taylorludwig** [comment]
Yeah makes sense. Even the [script itself](https://github.com/terraform-google-modules/terraform-google-project-factory/blob/master/modules/core_project_factory/scripts/preconditions/preconditions.py#L31) can fail with just a warning 

Looks like prior to https://github.com/terraform-google-modules/terraform-google-project-factory/pull/304 there was a [preconditions.sh](https://github.com/terraform-google-modules/terraform-google-project-factory/blob/d9fa967186e07d4800cac7e385b9cbdd165c0be9/modules/core_project_factory/scripts/preconditions.sh) file that would handle the warning instead of failing. 

So I incorrectly removed the `on_failure = "continue"` to mimic that functionality. 

I'll add back the `on_failure = "continue"` to the `preconditions` `local-exec`s but leave them removed from the modify service account runs (which is handled by glcoud module now anyways)

**Comment by anagas** [comment]
@taylorludwig the attribute on_failure is deprecated i would not add this again.

**Comment by Rycieos** [comment]
@anagas source for that? Are you misundd\erstanding this part of the CHANGELOG?
https://github.com/hashicorp/terraform/blob/master/CHANGELOG.md#user-content-01214-november-13-2019
> *Quoted references are deprecated:* In the depends_on and ignore_changes meta-arguments, quoted references like `"aws_instance.foo"` should be rewritten without the quotes, e.g. as `aws_instance.foo`.

**Comment by taylorludwig** [comment]
https://github.com/terraform-google-modules/terraform-google-project-factory/pull/357 is up

I set them as `on_failure = continue` (no quotes) as that is deprecated in 0.12 as you linked to. Thanks!
