### ISSUE TITLE
Lightweight project factory without dependency on terraform-google-gcloud

### ISSUE THREAD

**Issue by MajorBreakfast** [terraform-google-modules/terraform-google-project-factory#396]
The intention of the terraform-google-gcloud is to make the project factory module self-contained. However the use of it added two main downsides for use cases which do not require it (e.g. running this module inside a CI pipeline which can easily provide a preinstalled gcloud cli):

For each instance of the project factory, three instances of the terraform-google-gcloud are created which leads to 330MB (3x 110MB) being added to the modules folder. This is due to a zipped gcloud sdk contained within the artifact. See https://github.com/terraform-google-modules/terraform-google-gcloud/issues/37 for details. If that was not the case, the module would only be a few kilobytes in size. The `skip_download` flag cannot prevent the zipped sdk from being downloaded because it is always contained within the artifact.

Additionally, the terraform-google-gcloud creates various null resources and puts them into the terraform plan. These null resources frequently show up in subsequent plans because they store the absolute path to the gcloud cli https://github.com/terraform-google-modules/terraform-google-project-factory/issues/391 

I would like to propose the creation of a lightweight project factory module that does not depend on terraform-google-gcloud and instead requires a preinstall gcloud sdk. This flavor would be the ideal version intended for usage in CI pipelines which can easily provide a preinstalled gcloud sdk.

**Comment by adrian-gierakowski** [comment]
for those who, like myself, cannot afford to wait for the download size issue to be resolved, I have created [a fork](https://github.com/adrian-gierakowski/terraform-google-project-factory/tree/ag/use-terraform-google-gcloud-lite) of `terraform-google-project-factory` which uses a [lightweight copy](https://github.com/adrian-gierakowski/terraform-google-gcloud-lite) of  `terraform-google-gcloud` which is based on [this PR](https://github.com/terraform-google-modules/terraform-google-gcloud/pull/41) with all github history removed.  To get near instant `terraform init` replace 

```terraform
  source  = "terraform-google-modules/project-factory/google"
  version = "7.1.0"
```

with

```terraform
  source  = "git@github.com:adrian-gierakowski/terraform-google-project-factory.git?ref=df978e97721ad30011326024a5d20de35e5ac4e6"
```

in your terraform code

hopefully we can get this resolved upstream asap

**Comment by morgante** [comment]
#47 has been merged, so we should be able to address this by upgrading to the latest version of gcloud in this module.

**Comment by adrian-gierakowski** [comment]
@morgante I guess you meant https://github.com/terraform-google-modules/terraform-google-gcloud/pull/41? 

Besides, I think there is still one outstanding issue: removing all the binaries from git history (as mentioned in https://github.com/terraform-google-modules/terraform-google-gcloud/issues/37#issuecomment-612221939) because as far as I remember terraform performs a full clone of the repo when installing a module. According to https://github.com/terraform-google-modules/terraform-google-gcloud/issues/40 the repo weights over 1.3GB. I guess rewriting history is not an option so it might be necessary to create a new fresh repo for terraform-google-gcloud and archive the existing one.

**Comment by morgante** [comment]
I don't think that's true, when used from the registry it doesn't download full git history.

**Comment by adrian-gierakowski** [comment]
@morgante I've updated `terraform-google-modules/gcloud/google` to `version = "~> 1.0.0"` and then did:
```
cd examples/simple_project
env TF_LOG=DBUG terraform init
```

and this is what I see:
```
2020/04/16 09:56:45 [DEBUG] looking up module location from "https://registry.terraform.io/v1/modules/terraform-google-modules/gcloud/google/1.0.0/download"
2020/04/16 09:56:45 [TRACE] HTTP client GET request to https://registry.terraform.io/v1/modules/terraform-google-modules/gcloud/google/1.0.0/download
Downloading terraform-google-modules/gcloud/google 1.0.0 for project-factory.project-factory.gcloud_delete...
2020/04/16 09:56:45 [TRACE] ModuleInstaller: project-factory.project-factory.gcloud_delete terraform-google-modules/gcloud/google 1.0.0 is available at "git::https://github.com/terraform-google-modules/terraform-google-gcloud?ref=v1.0.0"
2020/04/16 09:56:45 [DEBUG] will download "git::https://github.com/terraform-google-modules/terraform-google-gcloud?ref=v1.0.0" to .terraform/modules/project-factory.project-factory.gcloud_delete
2020/04/16 09:56:45 [TRACE] fetching "git::https://github.com/terraform-google-modules/terraform-google-gcloud?ref=v1.0.0" to ".terraform/modules/project-factory.project-factory.gcloud_delete"
```

it's been stuck on the download for the last 15 minutes

not sure if that's because the module has not been cached in the registry yet or something, but regardless, I think it's worth reducing the size of the repo anyway

**Comment by morgante** [comment]
I'm very loathe to rewrite history without clear evidence that Terraform is doing the wrong thing and checking out old versions. Breaking old versions and destroying history is destructive to existing users and we'd need a really strong reason.

I just timed a `tf init` using the new module version and it took less than 2 seconds.

**Comment by adrian-gierakowski** [comment]
@morgante unfortunately after pooling latest master and running `terraform init` [as described above](https://github.com/terraform-google-modules/terraform-google-project-factory/issues/396#issuecomment-614517764) I get the same result: it gets stuck at:
```
2020/04/18 13:26:54 [TRACE] fetching "git::https://github.com/terraform-google-modules/terraform-google-gcloud?ref=v1.0.0" to ".terraform/modules/project-factory.project-factory.gcloud_delete"
```

and in my network activity is showing that data is being downloaded at around 1MB per second

It's possible that it happened quicker on your machine since terraform has previously cached the repo of the gcloud module and only had to pull the latest commits 

regarding rewriting history: I totally agree that it's not a good idea and that is why I suggested creating a new repo for the gcloud module

**Comment by morgante** [comment]
How are you specifying the module? It's just surprising to me because the module on my system is less than <1MB.

**Comment by adrian-gierakowski** [comment]
@morgante 

this is what I did:
```sh
git clone git@github.com:terraform-google-modules/terraform-google-project-factory.git
cd terraform-google-project-factory/examples/simple_project
env TF_LOG=DBUG terraform init
```

`git log -1 --format='%H'` results in: 2889db19aeb3322d6edf41d7b4aa40f320679650, so I've got the latest version from master

**Comment by adrian-gierakowski** [comment]
@morgante jest a quick update, it turns out that I was using slightly outdated version of terraform (v0.12.18), which seems to perform a full clone of the modules repo. After updating to v0.12.24 terraform init is nearly instant.

**Comment by morgante** [comment]
Thank you for the update! Looks like we can close this.
