### ISSUE TITLE
Shared vpc test should test shared_vpc project factory module

### ISSUE THREAD

**Issue by MajorBreakfast** [terraform-google-modules/terraform-google-project-factory#443]
https://github.com/terraform-google-modules/terraform-google-project-factory/blob/d28561cbd92838b991b30fb44d85951f1e732c8f/test/fixtures/vpc_sc_project/main.tf#L48

Currently it uses the root module. Hence, the shared_vpc remains untested.

Also the shared_vpc_access module is therefore untested. This module recently contained a bug (https://github.com/terraform-google-modules/terraform-google-project-factory/issues/442) which would have been detected if it was tested.

**Comment by bharathkkb** [comment]
Hi @MajorBreakfast 
It is actually tested here https://github.com/terraform-google-modules/terraform-google-project-factory/blob/d28561cbd92838b991b30fb44d85951f1e732c8f/test/fixtures/dynamic_shared_vpc/main.tf#L18

The reason why #442 was not detected was due to https://github.com/terraform-google-modules/terraform-google-project-factory/pull/441#pullrequestreview-468855846

**Comment by MajorBreakfast** [comment]
Ah i see... Terraform validation should have picked it up, but it didn‘t due to a bug in the Terraform version that was used. And that bug is unfortunately only fixed in 0.13. I‘m closing this issue because the code is tested after all
