### ISSUE TITLE
Fails with shared VPC being specified using a reference

### ISSUE THREAD

**Issue by harpenden** [terraform-google-modules/terraform-google-project-factory#47]
If I specify shared_vpc in a service project I receive following error during plan or apply. If I remove shared_vpc it works but creates a standalone project instead of a service project.

```
* module.service_project01.google_compute_subnetwork_iam_member.group_role_to_vpc_subnets:
google_compute_subnetwork_iam_member.group_role_to_vpc_subnets: value of 'count' cannot be computed
* module.service_project01.google_compute_shared_vpc_service_project.shared_vpc_attachment: google_compute_shared_vpc_service_project.shared_vpc_attachment: value of 'count' cannot be computed
* module.service_project01.google_project_iam_member.controlling_group_vpc_membership: google_project_iam_member.controlling_group_vpc_membership: value of 'count' cannot be computed
* module.service_project01.google_compute_subnetwork_iam_member.gke_shared_vpc_subnets: google_compute_subnetwork_iam_member.gke_shared_vpc_subnets: value of 'count' cannot be computed
* module.service_project01.google_compute_subnetwork_iam_member.service_account_role_to_vpc_subnets: google_compute_subnetwork_iam_member.service_account_role_to_vpc_subnets: value of 'count' cannot be computed
* module.service_project01.google_compute_subnetwork_iam_member.apis_service_account_role_to_vpc_subnets: google_compute_subnetwork_iam_member.apis_service_account_role_to_vpc_subnets: value of 'count' cannot be computed
* module.service_project01.google_project_iam_member.gke_host_agent: google_project_iam_member.gke_host_agent: value of 'count' cannot be computed
```

**Example resources:**
```

module "host_project01" {
  source            = "/modules/project-factory"
  random_project_id = "true"
  name              = "host-project-01"
  org_id            = "${var.organization_id}"
  billing_account   = "${var.billing_account}"
  activate_apis     = ["compute.googleapis.com"]
  credentials_path  = "${local.credentials_file_path}"
}

module "service_project01" {
  source            = "/modules/project-factory"
  random_project_id = "true"
  name              = "service-project01"
  org_id            = "${var.organization_id}"
  billing_account   = "${var.billing_account}"
  folder_id         = "${google_folder.prod.id}"
  shared_vpc        = "${module.host_project01.project_id}" # If I remove this it works but creates a standalone project.
  activate_apis     = ["compute.googleapis.com"]
  credentials_path  = "${local.credentials_file_path}"
  group_name        = "testgroup"
  group_role        = "roles/owner"
}
```

**Comment by crayfishx** [comment]
It seems to me this issue occurs when passing in a variable that references a computed variable in `host_project01`.  The `project_id` output variable traces back to the `temp_project_id` local var in the module which evaluates the value of `random_id.random_project_id_suffix.hex` - Terraform plan seems to fail when you try and pass the results of an output variable that derrives from a computed value as input into another module and then try and use that value in the `count` attributes of resources.

```
resource "google_compute_shared_vpc_service_project" "shared_vpc_attachment" {
  count = "${var.shared_vpc != "" ? 1 : 0}"
```

The problem here is that `var.shared_vpc` is being passed in from `module.host_project01.project_id` which maps back to `local.project_id` in outputs.tf, and further tracing this reveals it will eventually try and evaluate `temp_project_id` which will try and reference the yet uncomputed value from the random_id resource.

One workaround I can think of right now would involve adding a new input variable to project factory called `shared_vpc_enabled` as a boolean and using that to evaluate in situations such as;

```
resource "google_compute_shared_vpc_service_project" "shared_vpc_attachment" {
  count = "${var.shared_vpc_enabled == "true" ? 1 : 0}"
```
That would require users to specify both `shared_vpc_enabled = true` and `shared_vpc = <host project>` when calling the module - initial testing shows this would fix the errors.   I'm still digging into this so might find a better way....

**Comment by ingwarr** [comment]
@aaron-lane I can't reproduce this issue. As I see similar construction used in https://github.com/terraform-google-modules/terraform-google-project-factory/blob/master/examples/shared_vpc/main.tf and it works.

**Comment by morgante** [comment]
@ingwarr: That example is not the same. That example shows creating a host project, not a service project.

The key part of the issue is this variable:
```
  shared_vpc        = "${module.host_project01.project_id}" # If I remove this it works but creates a standalone project.
```

**Comment by aurelienlegrand** [comment]
**@aaron-lane**, I think I ran into the same issue.

Here is an extract of code showing the issue:
```
module "infra-host-project" {
  source  = "terraform-google-modules/project-factory/google"
  version = "~> 2.0"
  [...]
  
}
```

**Comment by aurelienlegrand** [comment]
@aaron-lane, I think I ran into the same issue.

Here is an extract of code showing the issue:
```
module "infra-host-project" {
  source                      = "terraform-google-modules/project-factory/google"
  version                     = "~> 2.0"
  random_project_id           = "true"
  [...]
}

module "project-factory" {
  source                      = "terraform-google-modules/project-factory/google"
  version                     = "~> 2.0"
  random_project_id           = "true"
  shared_vpc                  = "${module.infra-host-project.project_id}"
  [...]
}
```
With the above code, when I run a `terraform plan` command, I get this kind of errors 

```
Error: module.project-factory.module.project-factory.google_compute_subnetwork_iam_member.group_role_to_vpc_subnets: 1 error(s) occurred:

* module.project-factory.module.project-factory.google_compute_subnetwork_iam_member.group_role_to_vpc_subnets: index: Could not find 'regions' in '[{Variable (TypeString): }]' in:

${element(split("/", var.shared_vpc_subnets[count.index]), (index(split("/", var.shared_vpc_subnets[count.index]),"regions"))+1)}
[...]
```

If I use a static reference to a project_id for the last line (`shared_vpc`) it will work as intended and attach the service project to the Shared VPC in the host project.

**Comment by ingwarr** [comment]
@aaron-lane Thank you! I've reproduced it. So now I'm looking for a workaround.

**Comment by morgante** [comment]
I think it's possible to do this in a non-breaking way:

1. Update the core project factory to include an "enable_shared_vpc" variable which is used to enable/disable that resource (instead of looking at the `shared_vpc` flag).
2. In the root module, look at the `shared_vpc` variable and set the `enable_shared_vpc` variable  appropriately when passing it through to the inner module.
3. Add a `shared-vpc` (outer) submodule which requires a shared_vpc input and *always* sets `enable_shared_vpc` to true.
