### ISSUE TITLE
New subnet in sharedVPC recreates google_compute_subnetwork_iam_member.service_account_role_to_vpc_subnets

### ISSUE THREAD

**Issue by lanilim** [terraform-google-modules/terraform-google-project-factory#514]
We used a shared VPC setup in GCP where subnets are managed. We then run all our foundational terraform scripts to ensure that the tf state is still in sync. When adding new subnet in our sharedVPC project like so
{
      subnet_name           = "${local.subnet_12}"
      subnet_ip             = "${local.subnet_12_ip}"
      subnet_region         = "${local.subnet_12_region}"
      subnet_private_access = "true"
      subnet_flow_logs      = "true"
    }
>> which is from terraform-google-modules/network/google (version "~> 2.5.0")

Running TF script to the attached projects (version "~> 9.0.0") seem to recreate the array of google_compute_subnetwork_iam_member.service_account_role_to_vpc_subnets
Plan: 12 to add, 0 to change, 8 to destroy.

Expected result:
Just add new ones google_compute_subnetwork_iam_member.service_account_role_to_vpc_subnets

**Comment by morgante** [comment]
This is because we use `count` to manage the subnet IAM membership: https://github.com/terraform-google-modules/terraform-google-project-factory/blob/master/modules/core_project_factory/main.tf#L175

However, there shouldn't be any issue with reapplying configuration. Creating and deleting an IAM membership is a no-op.
