### ISSUE TITLE
SKIP_DELETE option 

### ISSUE THREAD

**Issue by czedyousfi** [terraform-google-modules/terraform-google-project-factory#688]
### TL;DR

Implement `skip_delete` in google_project resource. 

### Terraform Resources

```markdown
https://registry.terraform.io/providers/hashicorp/google/latest/docs/resources/google_project#example-usage
```

### Detailed design

```markdown
Hello ! 
It happens sometimes that you need to do a terraform destroy in your project. Without the "skip_delete" option, this will cause a project deletion and can be unwanted in some cases. The variable could be optional and set to False when not used.
```

**Comment by morgante** [comment]
We are unlikely to add this. If you want to destroy other resources but not the project, you should really be either:
1. deleting those other resources from your Terraform config
2. splitting the project creation into a separate Terraform root module.

Since this has multiple easy workarounds and we don't want to needlessly increase our API surface, this seems unnecessary.
